name: CI

on:
  push:
    branches: [ "Jlrty3" ]
  pull_request:
    branches: [ "Jlrty3" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-platform: 'android-34'
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build APK
        run: ./gradlew assembleDebug
        
      - name: Build APK - Release
        run: ./gradlew assembleRelease
